name: Deploy API to Heroku

on:
  push:
    branches:
      - main 
    paths: 
      - "api/**"
      - ".github/workflows/api_deploy_heroku.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ec-app-challenge" #Must be unique in Heroku
          heroku_email: "anilsonmonteiro@gmail.com"
          appdir: "api/" # <- This will point to the api folder in your project!
